CREATE TABLE IF NOT EXISTS public.memories (
  tenant_id STRING NOT NULL,
  agent_id STRING NOT NULL,
  memory_id UUID NOT NULL DEFAULT gen_random_uuid(),
  layer STRING NOT NULL,
  kind STRING,
  episode_id STRING,
  content STRING NOT NULL,
  embedding VECTOR(512),
  experience_body JSONB,
  exp_status STRING,
  source STRING NOT NULL,
  admission STRING NOT NULL,
  quarantine_expires_at TIMESTAMPTZ,
  state STRING NOT NULL DEFAULT 'fresh',
  pinned BOOL NOT NULL DEFAULT false,
  importance FLOAT NOT NULL DEFAULT 0.5,
  strength_anchor FLOAT NOT NULL DEFAULT 1.0,
  strength_anchor_at TIMESTAMPTZ NOT NULL,
  last_rewarded_at TIMESTAMPTZ NOT NULL,
  half_life_hours FLOAT NOT NULL,
  credited_success_count INT NOT NULL DEFAULT 0,
  evidenced_blame_count INT NOT NULL DEFAULT 0,
  revision INT8 NOT NULL DEFAULT 0,
  next_transition_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, agent_id, memory_id),
  UNIQUE INDEX memories_tenant_memory_uq (tenant_id, memory_id),
  CONSTRAINT memories_layer_ck CHECK (layer IN ('event', 'experience')),
  CONSTRAINT memories_exp_body_iff_experience_ck CHECK ((layer = 'experience') = (experience_body IS NOT NULL)),
  CONSTRAINT memories_exp_status_iff_experience_ck CHECK ((layer = 'experience') = (exp_status IS NOT NULL)),
  CONSTRAINT memories_exp_status_ck CHECK (exp_status IS NULL OR exp_status IN ('candidate', 'verified', 'superseded')),
  CONSTRAINT memories_source_ck CHECK (source IN ('user_asserted', 'tool_verified', 'agent_inferred', 'external_untrusted', 'derived')),
  CONSTRAINT memories_admission_ck CHECK (admission IN ('accepted', 'quarantined', 'rejected')),
  CONSTRAINT memories_state_ck CHECK (state IN ('fresh', 'consolidated', 'faded')),
  CONSTRAINT memories_importance_ck CHECK (importance BETWEEN 0 AND 1),
  CONSTRAINT memories_strength_anchor_ck CHECK (strength_anchor BETWEEN 0 AND 1),
  CONSTRAINT memories_half_life_ck CHECK (half_life_hours > 0),
  CONSTRAINT memories_credited_count_ck CHECK (credited_success_count >= 0),
  CONSTRAINT memories_blame_count_ck CHECK (evidenced_blame_count >= 0),
  CONSTRAINT memories_quarantine_expiry_ck CHECK ((admission = 'quarantined') = (quarantine_expires_at IS NOT NULL)),
  CONSTRAINT memories_accepted_embedding_ck CHECK (admission <> 'accepted' OR embedding IS NOT NULL),
  CONSTRAINT memories_quarantined_no_embedding_ck CHECK (admission <> 'quarantined' OR embedding IS NULL),
  CONSTRAINT memories_pin_accepted_ck CHECK (NOT pinned OR admission = 'accepted'),
  VECTOR INDEX mem_vec_idx (tenant_id, agent_id, embedding vector_cosine_ops),
  INDEX mem_due_idx (tenant_id, next_transition_at, memory_id),
  INDEX mem_pin_idx (tenant_id, agent_id, pinned, importance DESC)
)
