CREATE TABLE IF NOT EXISTS public.nightly_runs (
  tenant_id STRING NOT NULL,
  run_id UUID NOT NULL DEFAULT gen_random_uuid(),
  job_kind STRING NOT NULL,
  scheduled_for TIMESTAMPTZ NOT NULL,
  pipeline_version STRING NOT NULL,
  status STRING NOT NULL DEFAULT 'running',
  lease_expires_at TIMESTAMPTZ,
  attempt_count INT NOT NULL DEFAULT 1,
  batch_size INT NOT NULL,
  source_snapshot JSONB NOT NULL,
  source_fingerprint BYTES NOT NULL,
  model_id STRING,
  error_code STRING,
  error_message STRING,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, run_id),
  UNIQUE INDEX nightly_runs_schedule_uq (tenant_id, job_kind, scheduled_for, pipeline_version),
  UNIQUE INDEX nightly_runs_fingerprint_uq (tenant_id, job_kind, source_fingerprint, pipeline_version),
  CONSTRAINT nightly_runs_job_kind_ck CHECK (job_kind IN ('dream', 'reflection', 'transition')),
  CONSTRAINT nightly_runs_status_ck CHECK (status IN ('running', 'stale', 'completed', 'failed')),
  CONSTRAINT nightly_runs_attempt_count_ck CHECK (attempt_count >= 1),
  CONSTRAINT nightly_runs_batch_size_ck CHECK (batch_size > 0),
  CONSTRAINT nightly_runs_running_lease_ck CHECK (status <> 'running' OR lease_expires_at IS NOT NULL),
  INDEX nightly_runs_lease_idx (tenant_id, status, lease_expires_at)
)
