CREATE TABLE IF NOT EXISTS public.memory_rebuild_queue (
  tenant_id STRING NOT NULL,
  agent_id STRING NOT NULL,
  rebuild_id UUID NOT NULL DEFAULT gen_random_uuid(),
  deleted_derived_memory_id UUID NOT NULL,
  remaining_source_memory_ids UUID[] NOT NULL,
  originating_run_id UUID,
  status STRING NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  lease_expires_at TIMESTAMPTZ,
  last_error STRING,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  PRIMARY KEY (tenant_id, rebuild_id),
  UNIQUE INDEX memory_rebuild_queue_deleted_uq (tenant_id, deleted_derived_memory_id),
  CONSTRAINT memory_rebuild_queue_status_ck CHECK (status IN ('pending', 'processing', 'completed', 'abandoned')),
  CONSTRAINT memory_rebuild_queue_attempt_count_ck CHECK (attempt_count >= 0),
  CONSTRAINT memory_rebuild_queue_processing_lease_ck CHECK (status <> 'processing' OR lease_expires_at IS NOT NULL),
  CONSTRAINT memory_rebuild_queue_run_fk FOREIGN KEY (tenant_id, originating_run_id) REFERENCES public.nightly_runs (tenant_id, run_id),
  INDEX memory_rebuild_queue_claim_idx (tenant_id, status, lease_expires_at, created_at)
)
